# Numpy tutorial from the offical doccumentation website

## A little bit of knowledge of what Numpy is

In [15]:
# Import the numpy package
import numpy as np

In [16]:
"""
    NumPy (Numerical Python) is a package in Python that is often mainly used for Scientific comptation(e.g, Mathematical operations, basic linear algebra), etc. In addition Numpy leverages C pre-compiled code and has a fixed size at creation.

    Here are list of differences between List and Array in Python:
    -List:
        - The size can grow dynamically
        - The size isn't allocate contigously, instead it is scatter (behind the scence)
        - Can store various data types

    -Array:
        - The size is fixed at creation
        - The size is allocate contigously
        - Can only store same type of data types(usually numbers)
"""

# Creating a simple vector(1D array), more about what vector is will be explain later
vector = np.array([1,2,3,4,5])

In [17]:
vector

array([1, 2, 3, 4, 5])

In [18]:
"""
    A vector is 1D (1 Dimensional) Array. In addition to 1D a dimension in NumPy is often called axes. A vector has only 1 axes. Besides vectors, there are a Matrices (2 Dimensional) Array that has 2 axes, and tensors that has more than 2 axes.
"""

# Vector example
vector = np.array([1,2,3,4,5],dtype=np.int16)

# Matrix example
matrix = np.arange(15,dtype=np.float32).reshape(3,5) # Specified the data type of matrix with the keyword argument dtype

# Tensor example
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [19]:
vector

array([1, 2, 3, 4, 5], dtype=int16)

In [20]:
matrix

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]], dtype=float32)

In [21]:
tensor

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## Some of importants attribute of an array 

In [26]:
"""
    -ndarray.shape: This will return a tuple of integers, that represented each dimensions length or size
    -ndarray.ndim: Number of axes in an array
    -ndarray.size: Total of numbers in an array. This is equivalent to product of the shape of an array
    -ndarray.nbytes: Total usage of bytes memory of an array
    -ndarray.dtype: Describing the data type of an array. One can describe the array data type or specified the data type of an array using the keyword argument "dtype"
    -ndarray.itemsize: The size in bytes of each element in an array
"""

print(f"Vector consumed memory for about = {vector.nbytes} Bytes")
print(f"Each element of vector has a size for about = {vector.itemsize} Bytes")
print(f"Vector has shape for about = {vector.shape}")
print(f"Vector has a dtype of = {vector.dtype}")
print(f"Vector has total axes for about = {vector.ndim}")

Vector consumed memory for about = 10 Bytes
Each element of vector has a size for about = 2 Bytes
Vector has shape for about = (5,)
Vector has a dtype of = int16
Vector has total axes for about = 1
